add setting for date and time format
LeoColman/Petals pull request #189
Opened 2022-12-15 11:50 UTC by mkicina

This change resolves #67 by adding setting for date and time format.

2022-12-15 14:38 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/statistics/StatisticsPage.kt
> +  val settingsRepository = get<SettingsRepository>()
Let's change this guy here to come injected as a dependency, just as `UseRepository` is

2022-12-15 14:40 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  val dateFormatList = arrayOf("yyyy-MM-dd", "yyyy/MM/dd", "dd-MM-yyyy", "dd.MM.yyyy")
We have people that insist on using 
MM/dd/yyyy or similars as date formats.

Maybe we should add that format in

2022-12-15 14:41 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  val dateFormatList = arrayOf("yyyy-MM-dd", "yyyy/MM/dd", "dd-MM-yyyy", "dd.MM.yyyy")
It's not very usual to use `Array`, even if it's sometimes more """optimized""" than a list.
Let's change this to be a `listOf` instead

2022-12-15 14:42 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  val dateFormat = datastore.data.map { it[DateFormat] ?: dateFormatList[0] }
Not sure if I prefer `list[0]` or `list.first()`/`list.firstOrNull()`.
I think in the end they convey the same information, and the list is close enough for this not to matter

2022-12-15 14:43 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +  dateFormatList: Array<String> = arrayOf(),
If we change SettingsRepository to use a `List` this needs to be changed as well

2022-12-15 14:44 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +  timeFormatList: Array<String> = arrayOf(),
If we change SettingsRepository to use a List this needs to be changed as well

2022-12-15 14:44 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +  timeFormatList: Array<String> = arrayOf(),
If we change SettingsRepository to use a List this needs to be changed as well

2022-12-15 14:44 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +  dateFormatList: Array<String> = arrayOf(),
If we change SettingsRepository to use a List this needs to be changed as well

2022-12-15 14:46 UTC, LeoColman approved these changes
br/com/colman/petals/settings/SettingsRepositoryTest.kt:10

We should include unit tests to test the new settings.
One thing that I want tested is that all date formates are valid as per `DateTimeFormatter`. Same goes for the time formats

2022-12-15 14:48 UTC, LeoColman requested changes
br/com/colman/petals/settings/SettingsRepositoryTest.kt:10

We should include unit tests to test the new settings.
One thing that I want tested is that all date formates are valid as per DateTimeFormatter. Same goes for the time formats

2022-12-15 14:48 UTC, LeoColman commented
The Linter isn't happy about your changes.
Please run `./gradlew detekt` locally and check what it's complaining about

2022-12-15 20:58 UTC, mkicina commented
Hi, I have problem with running test locally.

Can you tell me how can I accomplish that?

2022-12-15 22:28 UTC, mkicina commented
I somehow managed to create and pass tests, althougt I am not sure if it is right approach to test it. If you add invalid date/time format, test throw exception, and then test fail.

Also lint problems were resolved.

If you will have time, you can give me feedback. Thx!

2022-12-16 14:51 UTC, LeoColman requested changes

2022-12-16 14:51 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/use/LastUseDateTimer.kt
> +  val dateString = DateTimeFormatter.ofPattern(
I like the solution!
This will make us lose a bit of precision in seconds and millis. I don't know how much users like to see that accuracy on the timestamp.

We can open another issue to discuss this

2022-12-16 14:51 UTC, LeoColman commented on app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
> +    value shouldBe true
We can reduce this to

```
val dateFormatList = target.dateFormatList
shouldNotThrowAny {
  dateFormatList.forEach { DateTimeFormatter.ofPattern(it) }
}

```

2022-12-16 14:51 UTC, LeoColman commented on app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
> +  }
Same thing for this guy

2022-12-16 14:51 UTC, LeoColman commented on app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
>  class SettingsRepositoryTest : FunSpec({
Please add tests that we are persisting the date and time settings correctly

2022-12-16 15:03 UTC, mkicina commented on app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
>  class SettingsRepositoryTest : FunSpec({
Please can you be more specific what do you want from that new tests? I am not sure if I understand you correctly.

2022-12-16 16:13 UTC, LeoColman commented on app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
>  class SettingsRepositoryTest : FunSpec({
```
 test("Defaults currency icon to $") {
    target.currencyIcon.first() shouldBe "$"
  }
  test("Changes the currency to the specified one") {
    target.setCurrencyIcon("R$")
    target.currencyIcon.first() shouldBe "R$"
  }
```

this is the test for the Currency setting. Do you see that we test that when we set the currency it is actually what we set when we retrieve it?

2022-12-16 16:14 UTC, LeoColman commented on app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
>  class SettingsRepositoryTest : FunSpec({
I want the same test for Date and Time

"When I set the date to X, getting the date from the repository should return X"

So that we know we are not returning only the default value

2022-12-17 12:29 UTC, mkicina commented
I added requested tests, hope it is ok.

2022-12-17 12:29 UTC, mkicina commented on app/src/test/kotlin/br/com/colman/petals/settings/SettingsRepositoryTest.kt
>  class SettingsRepositoryTest : FunSpec({
Thanks for explanation.

2022-12-17 18:35 UTC, LeoColman approved these changes

2022-12-17 18:35 UTC, merged

2022-12-17 18:35 UTC, LeoColman commented
Thanks for the contribution!
Cheers 🎉

2022-12-17 18:36 UTC, mkicina commented
No problem, happy to help!

2022-12-17 18:44 UTC, LeoColman commented
Released in 3.5.0.