Toast message added
LeoColman/Petals pull request #247
Opened 2023-02-13 04:55 UTC by azmatroshan

I have added a toast message. When user wants delete "Use", an alertDialog will pop up to confirm that user really wants to delete "Use" and then if user clicks "Yes" then "Use" will be deleted and a toast message showed up.

screenshots: -

![screenshot#1](https://user-images.githubusercontent.com/93484428/218372853-31f0bd78-d952-43f2-bea8-bbadce673186.jpg)
![screenshot#2](https://user-images.githubusercontent.com/93484428/218372891-c3807d16-74b4-45f6-b2d5-420476678c2f.jpg)

2023-02-13 17:49 UTC, LeoColman commented
Detekt is complaining about some issues related to code formatting:

<details>
<summary>Details</summary>

> Task :app:detekt
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:146:126: Argument should be on a separate line (unless all arguments can fit a single line) [ArgumentListWrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:147:9: Missing newline before ")" [ArgumentListWrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:157:54: Argument should be on a separate line (unless all arguments can fit a single line) [ArgumentListWrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:157:103: Argument should be on a separate line (unless all arguments can fit a single line) [ArgumentListWrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:162:1: Missing newline before ")" [ArgumentListWrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:146:88: Missing newline after "," [Wrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:144:16: Missing newline after "(" [Wrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:149:23: Missing newline before ")" [Wrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:146:98: Missing newline before "}" [Wrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:160:40: Missing newline after "{" [Wrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:168:31: Missing newline before "}" [Wrapping]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:135:1: Exceeded max line length (120) [MaximumLineLength]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:140:23: Missing spacing before "{" [SpacingAroundCurly]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:142:28: Missing spacing after "{" [SpacingAroundCurly]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:142:53: Missing spacing before "}" [SpacingAroundCurly]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:163:1: Missing spacing before "}" [SpacingAroundCurly]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:145:1: Unexpected indentation (12) (should be 10) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:145:23: Unexpected indentation (10) (should be 12) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:147:1: Unexpected indentation (10) (should be 12) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:148:3: Unexpected indentation (12) (should be 10) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:149:1: Unexpected indentation (14) (should be 10) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:150:21: Unexpected indentation (8) (should be 10) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:163:23: Unexpected indentation (10) (should be 8) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:164:15: Unexpected indentation (8) (should be 10) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:165:47: Unexpected indentation (8) (should be 10) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:167:1: Unexpected indentation (4) (should be 8) [Indentation]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:140:5: Missing spacing after "if" [SpacingAroundKeyword]
/home/runner/work/Petals/Petals/app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt:135:1: Line detected, which is longer than the defined maximum line length in the code style. [MaxLineLength]

</details>

You can run `./gradlew detekt` locally to display all the errors in your command line

2023-02-13 17:51 UTC, LeoColman requested changes

2023-02-13 17:51 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
> +          Toast.makeText(context, "Deleted Successfully", Toast.LENGTH_SHORT).show() }, colors = ButtonDefaults.buttonColors(Color.White)) {
This string should be Internationalized

2023-02-13 17:51 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
> +          Text(text = "Yes")
This string should be internationalized. I believe 'yes' is already an internationalized string

2023-02-13 17:51 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
> +          Icon(imageVector = Icons.Outlined.Delete, contentDescription = "delete")
This string should be internationalized, and the same one should be used in both `text` and `contentDescription`

2023-02-13 17:51 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
> +      text = { Text(text = "Do you really want to delete this?")},
This string should be internationalized.
Also, 'this' is a bit too generic. We should add the use information instead

2023-02-13 17:51 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/use/UseCard.kt
> +      dismissButton = { Button(onClick = { showDialog.value = false }, colors = ButtonDefaults.buttonColors(Color.White)) { Text(text = "No") } }
This string should be internationalized. I think 'no' is already internationalized too

2023-02-14 06:23 UTC, azmatroshan commented
@LeoColman 
I have made changes that you requested and committed it with commit message "added string resources and modified delete feature".

here are the final screenshots  of app: 

![Screenshot #1](https://user-images.githubusercontent.com/93484428/218655180-9024dcff-7a41-42a7-b821-568f80c42a52.jpg)
![Screenshot #2](https://user-images.githubusercontent.com/93484428/218655195-147e93c6-b413-46ef-89ca-8a457e86c88d.jpg)

2023-02-15 16:41 UTC, LeoColman approved these changes

2023-02-15 16:46 UTC, merged