Implemented the App Rating Functionality
LeoColman/Petals pull request #605
Opened 2024-06-11 10:08 UTC by fenil09

Integrated the Rating dailog feature for Petals, showing the dialog only after 10 clean opens for the app and terminating the dialog if the user has opted not be asked again.

2024-06-20 00:20 UTC, LeoColman requested changes

2024-06-20 00:20 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
> +      MainScreen(this)
This change must be moved to the `playstore` variant, and not the default one.
This is because Github Releases and F-Droid have no concept of rating

2024-06-20 00:21 UTC, LeoColman commented
Thanks for the PR @fenil09 !
I left a comment and I think you're able to take a look at the workflows as well

2024-06-20 04:48 UTC, fenil09 commented on app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
> +      MainScreen(this)
Thanks Leo for reaching out would be moving the changes to the playstore variant.

2024-06-21 11:23 UTC, fenil09 commented on app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
> +      MainScreen(this)
Hii Leo, hope you are doing fine, I moved the changes to the playstore variant and made a new commit to the branch, It is the same PR,  let me know if anything. Thanks

2024-06-21 22:16 UTC, LeoColman requested changes
PR shaping up nicely!

Thanks for the contribution, there are still a few steps to go :)

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/AppRating/AppRating.kt
> +    title = { Text(text = "Rate our Petals") },
🟡 We need to extract this guy to a translatable string (i.e. strings.xml). 
"Rate us on Play Store" reads better IMO

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/AppRating/AppRating.kt
> +    text = { Text(text = "Please take some time to rate our app") },
🟡 Need to extract string

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/AppRating/AppRating.kt
> +        Text(text = "Rate now")
🟡 Need to extract string

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/AppRating/AppRating.kt
> +        Text(text="Dont ask Again")
🟡 Need to extract string

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/AppRating/AppRating.kt
> +}
🔴 Main screen shouldn't be moved inside another component. We need another way out of this

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
> +      MainScreen(this)
🔴 It's still around 👻

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/utils/Preferences.kt
> +    val Key_Dont_Ask_Again = "dontaskagain"
🔵 Let's go with `PascalCaseVariables` instead of `Pascal_Snake_Variables`

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/utils/Preferences.kt
> +    val Key_Dont_Ask_Again = "dontaskagain"
🔵 Let's also make naming and string consistent

2024-06-21 22:16 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/utils/Preferences.kt
> +    val uage_Threshold = 10
🔵 Typo on this guy and not PascalCase

2024-06-21 22:16 UTC, LeoColman commented on app/src/playstore/kotlin/br/com/colman/petals/playstore/AppRating.kt
🔴 This whole file is a copy of AppRating in the main package.

We either keep everything on the main package or we bring them all to the playstore variant (my preferred solution), but in this case we don't need to duplicate.

2024-06-21 22:16 UTC, LeoColman commented on settings.gradle.kts
> +}
👍🏻

2024-06-23 08:18 UTC, fenil09 commented
Hey Leo, Thanks for pointing out all the changes, I would be working upon them and try to create a commit having all the changes been implemented.

2024-07-17 21:34 UTC, LeoColman commented
Hi @fenil09 ! Quick ping on this one

2024-07-17 22:34 UTC, fenil09 commented
Hey Leo, Sorry for the delay had been busy in some other work, would be trying to implement the changes in the PR ASAP.

2024-07-17 22:37 UTC, LeoColman commented
Just checking in, no worries;)

2024-08-18 23:24 UTC, LeoColman commented
Hey @fenil09 !!
Maybe it's better to re-open the issue for when you have more time?

2024-08-18 23:29 UTC, fenil09 commented
Hey Leo, That sounds perfect. Sorry for the delays have been stuck in something.

2024-08-18 23:54 UTC, LeoColman commented
Don't worry!
Hopefully I'll see you around again :)

2024-08-18 23:54 UTC, closed without merging