:rotating_light: Fix "Average use per X" card alignments #640
LeoColman/Petals pull request #649
Opened 2024-07-17 17:02 UTC by gBL17

2024-07-17 20:14 UTC, gBL17 commented
https://github.com/user-attachments/assets/aeb2c56d-2161-4e2f-9a2d-f304ab358941

2024-07-17 21:33 UTC, LeoColman requested changes
Stack cards vertically

2024-07-18 15:57 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/statistics/card/AverageUseCard.kt
> +  Row(Modifier, spacedBy(6.dp), CenterVertically) {
```suggestion
  Row(Modifier, spacedBy(8.dp), CenterVertically) {
```

2024-07-18 15:58 UTC, LeoColman approved these changes

2024-07-18 16:01 UTC, merged