✨ Change date and time picker to material design
LeoColman/Petals pull request #663
Opened 2024-07-30 17:43 UTC by panwar2001

### DATE & TIME PICKER
<img src="https://github.com/user-attachments/assets/0f3ac47c-e4d1-4dcf-bbbb-013af0a7a577" style="border-radius: 20px;" width="200px" alt="" />

<img src="https://github.com/user-attachments/assets/7b1fe9ec-606c-40da-814d-f0645cbf8c4d" style="border-radius: 20px;" width="200px" alt="" />

<img src="https://github.com/user-attachments/assets/be3fedec-cc94-4646-94ed-4a364cfc28b7" style="border-radius: 20px;" width="200px" alt="" />

solution for issue #601

2024-07-31 10:05 UTC, panwar2001 commented
what else can be done?
@LeoColman

2024-08-01 16:46 UTC, LeoColman commented
Thanks for the contribution @panwar2001 !! It's awesome to have people interested in this project :)

One thing I'd like to address before merging the PR and taking it off your hands is removing the 12H version of the TimeDialog and keep only the 24H version for now. We have issue #618 to take care of letting the user choose which format they preffer.

2024-08-01 17:31 UTC, panwar2001 commented
### 24 hour mode time picker

<img src="https://github.com/user-attachments/assets/3c402912-40d6-4c92-8010-fd81e315273b" style="border-radius: 20px;" width="200px" alt="" />

2024-08-01 22:41 UTC, LeoColman requested changes

2024-08-01 22:41 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/components/TimePicker.kt
> +import com.vanpra.composematerialdialogs.MaterialDialogState
We are still using this guy around.
Is this a missimport? We should be able to ditch vanpra dialogs altogether

2024-08-02 04:40 UTC, panwar2001 commented
Removed the vanpra library usage 
but , there is a warning message in other files as material and material3 library is used together.

![image](https://github.com/user-attachments/assets/8dbf7830-2039-44d5-acb5-47c8f0e7e992)

2024-08-02 11:05 UTC, panwar2001 commented on app/src/main/kotlin/br/com/colman/petals/components/TimePicker.kt
> +import com.vanpra.composematerialdialogs.MaterialDialogState
okay

2024-08-03 00:34 UTC, LeoColman approved these changes

2024-08-03 00:35 UTC, merged

2024-08-03 00:35 UTC, LeoColman commented
I think we are OK on having those warnings until we migrate all components to Material3.

Thanks for the contribution @panwar2001 !!