💸 Added option to buy ad-free version of the app on PlayStore
LeoColman/Petals pull request #698
Opened 2024-09-07 14:10 UTC by rahim001-sudo

2024-09-07 17:24 UTC, LeoColman commented
@rahim001-sudo If you take a look, each individual check have details on why they failed

2024-09-07 18:43 UTC, rahim001-sudo commented
@LeoColman  Yes 3 of them failed. Also Build Universal Apk (Fdroid apk) says unresolved reference for the code i have done.
i think i will study the project structure more now for the next PR. also in Studio it was working. I had used playstoreDebug as primary so i thought we are good to go 😄 .

2024-09-07 19:05 UTC, rahim001-sudo commented
@LeoColman  i have made the fix . i think now the checks should pass.

2024-09-08 01:26 UTC, LeoColman requested changes
All in all a very good PR!

I left some comments we need to address before moving forward

2024-09-08 01:26 UTC, LeoColman commented on app/build.gradle.kts
> +  implementation(libs.play.services.billing)
🔴 We don't want the billing details to leak out of the PlayStore module.

That's because they require many permissions and libraries that won't be used outside of it.
For that I think we'll need to do a couple of changes on the design

2024-09-08 01:26 UTC, LeoColman commented on app/src/debug/AndroidManifest.xml
> +    <uses-permission android:name="com.android.vending.BILLING" />
🔴 This needs to be removed

2024-09-08 01:26 UTC, LeoColman commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="com.android.vending.BILLING" />
🔴 This needs to be moved to the PlayStore manifest

2024-09-08 01:26 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/InAppPurchaseUtil.kt
> +class InAppPurchaseUtil(val context: Context) : PurchasesUpdatedListener {
🔴 This should be moved to be inside the PlayStore variant

2024-09-08 01:26 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/PetalsApplication.kt
> +}
I think that this needs to be moved as well

2024-09-08 01:26 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/InAppPurchaseUtil.kt
> +  fun init() {
🟡 It's probably better to use Kotlin's init here instead of a custom init() function

2024-09-08 01:26 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
🟡 I think we can use the SharedProperties for this, but probably can also be moved to the playstore variant just to keep things separated

2024-09-08 01:26 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
🟡 I think this guy could instead be part of the 'AdView' function.

1 - We don't have Ad-Free purchases outside the PlayStore
2 - We want to make the "Remove ads" a bit more discrete but still visible on the ad

Something like this was in my mind:

![image](https://github.com/user-attachments/assets/e0be83cb-dce7-4f34-a1e1-e9448860baa5)

2024-09-08 06:34 UTC, rahim001-sudo commented
Yes i will make those changes.
Please just now i was trying to test workflow so i had done a commit. i think that is asking for workflow review here. 
So please dont consider this as done. i am making changes as of now.

2024-09-09 06:16 UTC, rahim001-sudo commented on app/src/debug/AndroidManifest.xml
> +    <uses-permission android:name="com.android.vending.BILLING" />
Done

2024-09-09 06:17 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/InAppPurchaseUtil.kt
> +class InAppPurchaseUtil(val context: Context) : PurchasesUpdatedListener {
Done

2024-09-09 06:17 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/PetalsApplication.kt
> +}
Yes moved done.

2024-09-09 06:20 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
Yes but i am afraid that it might overlap on Ads Edges or we might end up with a violation as its a clickable and very close to Ads. as per my current knowledge.

If violation is not  possible i can move it there as well. As a premium(Crown) Icon button.

2024-09-09 06:21 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
Yes i will move it to playstore variant for separation of things.

2024-09-09 07:19 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
Also shared properties means we create it as module (like a library)right ?.
as of now i have moved it to playstore variant creating a different class similar to SettingsRepository.

2024-09-10 12:02 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
@LeoColman Hello Leo any update on this.

2024-09-13 13:18 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
yes, that works fine.

2024-09-13 13:23 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
Sorry, I lost the notification on your changes and actually thought I was waiting for you 😅
Good use of a ping although I missed it too

---

I thought that maybe we could introduce a row between the end of the bottom navigation and the ads.

> violation as its a clickable and very close to Ads. as per my current knowledge.

You're absolutely right, and I wouldn't notice this until I got the message from Google.

What about placing it on the top App Bar? It's a little bit crowded at the moment, but I think a "Remove ads"  crown that shows up until it's purchased wouldn't add too many things, I think.

I also thought about these icons, but the crown idea works too:

![image](https://github.com/user-attachments/assets/e8376dde-b243-4be8-a01a-d0aecb9d664d)

2024-09-14 07:57 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
Yes happens .
We can add it to the topBar (the first icon as per image mentioned) . 
Can you guide me on this a Bit.
we have added the inAppPurchase Code in playstore variant. and we dont want to expose it outside of that module.
Should i create a common module having a topBar class and refer that it in main/debug  and playstore differently with function parameters?.
or keep the code as it is and just add a flag isPlayStore in TopAppBar composable function and handle it there only?.

2024-09-14 07:57 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
Yup Done.

2024-09-14 08:01 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
I am more leaned towards the first option as it keeps things separated. But just wanted to confirm this part so that we can start working on other issues.

2024-09-14 13:52 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
Damn, having multiple variants is hard 😅

The flag wouldn't work I think, as we need the AdSettingsRepository

I'm wondering if there is a way to define the same method in both variants and have Android decide which one to call. 

Otherwise I agree the likely best solution is having a common module where both can access the top bar

2024-09-14 16:34 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
Yaa flags would mess things up more.
Well i had also thought of passing  composable lambda functions into TopAppBar method  

`fun MyTopAppBar(navController: NavController, options: @Composable() (() -> Unit)?=null) {`
from debug it will be null and from playstore our adFreeIcon.

it works but feels like cheating  :sweat_smile:  .
So lets go with the commons module as of now.

2024-09-15 15:49 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
@LeoColman  
Please let me know if i am making sense or getting confused .
Sorry i got little confused or may be little unsure :cry:  . 
 
Even if we would create a common module at project level  and keep the AdFreeIcon inside the playstore variant.
after the module creation we will have to pass it again to the commons module in some form (Possibly lamda again).

2024-09-15 17:11 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
@LeoColman 
Sorry for asking a lot of queries :sweat_smile:   
I thought a lot but even if we do a common AppBar at Root level and as of now we have our adFreeIcon limited to playStore module. we will have to pass it somehow to commons module and also move appbar dependencies as well  .

I hope i am making sense.

if thats true or makes sense.
then we can directly do it as lamda  or like this below snippet in playstore variant.

`TopAppBar{
                Box( Modifier
                  .padding(16.dp)
                  .height(56.dp)
                  .fillMaxWidth()) {
                  Row (modifier = Modifier.fillMaxWidth(),
                    Arrangement.SpaceBetween,
                    Alignment.CenterVertically)
                  {
                    AppAndVersionName()
                    Row(Modifier, spacedBy(16.dp)) {
                      ImportExportButtons()
                      AdFreeListItem() // our icon like this if not passed as lambda
                      InfoSettingsButton(navController)
                    }
                  }
                }
              }`

2024-09-15 17:13 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
AppBar dependencies  like it has reference to  **use** module which needs repo and more of that if i am not wrong.

2024-09-15 22:56 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
> fun MyTopAppBar(navController: NavController, options: @Composable() (() -> Unit)?=null) {
from debug it will be null and from playstore our adFreeIcon.

I like this idea, actually.

It's indeed a bit janky, but lifts our problem away. Maybe that's the way to go as lifting dependencies to a common module doesn't sound like it will work

2024-09-16 10:50 UTC, rahim001-sudo commented on app/src/main/kotlin/br/com/colman/petals/settings/view/listitem/AdFreeListItem.kt
> +fun AdFreeListItem() {
I have done the changes as per comments. Please review and let me know.

2024-09-16 17:42 UTC, rahim001-sudo commented
I can see some commits have happened as of now its 19 so i think we will squash it . but before that  is the PR Good  or any changes are required.

2024-09-17 02:48 UTC, LeoColman commented
Yes, so far the PR is amazing, and your communication has been great!

I'm running some tests on my end now to see if changes are needed

2024-09-17 16:51 UTC, rahim001-sudo commented
Thanks @LeoColman .
Yes please let me know when done.

on a side note I am learning from this Repo actually as of now (Jetpack components,Koin, Github CI/CD and stuff and commands).

2024-09-18 20:55 UTC, LeoColman commented
I think we are good to go!

I tested with real Playstore items on two different phones and it seems to work well
Thanks for the contribution @rahim001-sudo !!

2024-09-18 20:55 UTC, LeoColman approved these changes

2024-09-18 21:06 UTC, merged

2024-09-19 15:16 UTC, LeoColman commented
As a token of symbolic gratitude, please take these promo codes for ad-free google play petals :)
[promotion_codes.csv](https://github.com/user-attachments/files/17061834/promotion_codes.csv)

I imagine of course as you reached the repository that you would probably use the ad-free versions anyway :D

2024-09-21 11:53 UTC, rahim001-sudo commented
@LeoColman Thank you so much for the promo codes. Means a lot.
I would have used them.  but I dont consume weed/or any substance  as of now😅. 

(alcohol ban 👀) :D.

Sorry i had not opened notifications tab so missed it.