⚙️ Add app language selection setting
LeoColman/Petals pull request #725
Opened 2024-10-04 15:24 UTC by rubenquadros

A language selection setting is added to the settings page. The `MainActivity` now extends `AppCompatActivity` to handle changing the app language. More info on this here:
https://developer.android.com/guide/topics/resources/app-languages#androidx-impl

Closes #678

2024-10-05 01:05 UTC, LeoColman requested changes
Left a few comments.

Your code is pretty much what I had in mind! Cool :D

2024-10-05 01:05 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
🟡 Smells a lot like an enum class to me.

2024-10-05 01:05 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +      AppCompatDelegate.setApplicationLocales(appLocale)
🟡 I believe it's not necessary to use AppCompat.

On Test files I used this:

```
private fun MainActivity.setLocale(locale: Locale) {
  val resources = baseContext.resources
  Locale.setDefault(locale)
  val config = resources.configuration
  config.setLocale(locale)
  resources.updateConfiguration(config, resources.displayMetrics)
  runOnUiThread { recreate() }
}
```

Although specific to the test case, it wasn't necessary to use AppCompat. I'm not against it, but it's a big change that I need to understand better

2024-10-05 03:10 UTC, rubenquadros commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
Yes, this make sense!

2024-10-05 03:14 UTC, rubenquadros commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +      AppCompatDelegate.setApplicationLocales(appLocale)
I can give this a try. I wanted to use the newer API and this API works with `AppCompatActivity`. You can read more about it here: https://developer.android.com/guide/topics/resources/app-languages#androidx-impl

It's your call tho on which API we should go with :)

2024-10-05 03:15 UTC, rubenquadros commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/AppTheme">
Change is related to https://github.com/LeoColman/Petals/pull/725#discussion_r1788471670

2024-10-05 03:15 UTC, rubenquadros commented on app/src/main/kotlin/br/com/colman/petals/MainActivity.kt
> +class MainActivity : AppCompatActivity(), CoroutineScope by CoroutineScope(Dispatchers.Main) {
Change is related to https://github.com/LeoColman/Petals/pull/725#discussion_r1788471670

2024-10-07 16:30 UTC, rubenquadros commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +      AppCompatDelegate.setApplicationLocales(appLocale)
Hey @LeoColman! Did you have a chance to look at this? :)

2024-10-07 21:12 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +      AppCompatDelegate.setApplicationLocales(appLocale)
Ok, I was thinking AppCompat was something from the past, that's what mostly caught my attetion.

So, I'm assuming it's the right way to go. We should use your way

2024-10-08 01:22 UTC, LeoColman requested changes

2024-10-08 04:49 UTC, rubenquadros commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
Okay, let me track a look at this and get back!

2024-10-08 18:03 UTC, rubenquadros commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsView.kt
> +      settingsRepository.setAppLanguage(language) //save it to storage
Removed this and now we rely on the library

2024-10-08 18:10 UTC, rubenquadros commented on app/src/main/kotlin/br/com/colman/petals/settings/SettingsRepository.kt
> +  }
[AppCompatDelegate.getApplicationLocales()](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#getApplicationLocales()) this gives the users preferred locale which we set using `AppCompatDelegate.setApplicationLocales(appLocale)`. I'm not sure if we will get a list of supported locales

2024-10-08 23:33 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/AppLanguages.kt
> +      }
🟡
```suggestion
      return entries.firstOrNull { it.code == code }?.name ?: English.name
```

2024-10-08 23:34 UTC, LeoColman commented on app/src/main/kotlin/br/com/colman/petals/settings/AppLanguages.kt
> +        else -> English.code
```suggestion
      return entries.firstOrNull { it.name == languageName }?.code ?: English.code 
```

2024-10-08 23:35 UTC, LeoColman requested changes
Getting close.
There are a few changes to make and fix the linter complaints then I think we are good to go!

2024-10-09 16:10 UTC, rubenquadros commented
> Getting close. There are a few changes to make and fix the linter complaints then I think we are good to go!

What do we do about `Enum entry names should match the pattern` for `AppLanguage`? 😬

2024-10-09 16:15 UTC, LeoColman commented
I think we can go with having the English name as the enum name and a variable inside the enum having a string with the localized name.

I agree with detekt that it's a bit weird to have enums with cyrilic 😂

2024-10-09 20:35 UTC, LeoColman approved these changes
Great PR!
I'll test locally and merge.

2024-10-09 20:45 UTC, LeoColman requested changes
@rubenquadros Couldn't get it to work here :/


https://github.com/user-attachments/assets/84f79434-688e-43ac-a63f-ffae6ab321b5

2024-10-10 15:43 UTC, rubenquadros commented
> @rubenquadros Couldn't get it to work here :/
> 
>  Screencast.from.2024-10-09.17-43-43.mp4

Can you share the device details? Could have missed some version specific changes

2024-10-10 15:49 UTC, LeoColman commented
It's an emulator:

`Properties
avd.ini.displayname              Pixel 2 API 33
avd.ini.encoding                 UTF-8
AvdId                            Pixel_2_API_33
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile      
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:55acbc835978f326788ed66a5cd4c9a7
hw.device.manufacturer           Google
hw.device.name                   pixel_2
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   420
hw.lcd.height                    1920
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         33
image.sysdir.1                   system-images/android-33/google_apis/x86_64/
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.id                           google_apis
vm.heapSize                      228
`

2024-10-10 17:27 UTC, rubenquadros commented
Yes it does not seem to be working with a fresh install😭 When I was making the changes and testing it was working. I will have to check what is happening. It would be great if you also take a look. More eyes the better! 

https://github.com/user-attachments/assets/51b6c2f7-cdfe-45db-a4c8-d7397089f5d0

2024-10-10 17:44 UTC, rubenquadros commented
Nvm I got the issue. It was caused by yesterday's refactoring:
```
 fun getAppLanguageCode(languageName: String): String {
      return entries.firstOrNull { it.name == languageName }?.languageCode ?: English.languageCode
    }
```

Notice it? It should be `it.languageName` and not `it.name` 😝

2024-10-10 18:37 UTC, LeoColman approved these changes

2024-10-10 18:41 UTC, LeoColman commented
Thanks @rubenquadros ! Good Job :D

2024-10-10 18:45 UTC, merged